version: '3'

services:

  bot-channel-admin:
    build: .
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: "on-failure"
    environment:
      - NODE_ENV=development
      - PROJECT_MODE=development
